"""
Alert management system for IDPS
Handles alert generation, storage, and notifications
"""

from datetime import datetime, timedelta
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import threading
import queue
import json
import os
import sys
from collections import deque

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from models import Alert, db

# Import broadcast function (will be set by routes)
broadcast_new_alert = None

def set_broadcast_function(func):
    """Set the broadcast function for real-time alerts"""
    global broadcast_new_alert
    broadcast_new_alert = func

class AlertManager:
    def __init__(self):
        self.alert_queue = queue.Queue()
        self.alert_history = deque(maxlen=1000)  # Keep last 1000 alerts
        self.email_enabled = os.environ.get('EMAIL_ENABLED', 'False').lower() == 'true'
        self.slack_enabled = os.environ.get('SLACK_ENABLED', 'False').lower() == 'true'
        self.alert_count = 0
        self.critical_count = 0
        self.high_count = 0
        self.medium_count = 0
        self.low_count = 0
        self.alert_counts_history = deque(maxlen=60)  # For trend charts
        
        # Email configuration
        self.smtp_server = os.environ.get('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.environ.get('SMTP_PORT', 587))
        self.sender_email = os.environ.get('ALERT_EMAIL', 'security@rileyfalcon.com')
        self.sender_password = os.environ.get('EMAIL_PASSWORD', '')
        self.admin_emails = os.environ.get('ADMIN_EMAILS', 'admin@rileyfalcon.com,security@rileyfalcon.com').split(',')
        
        # Slack configuration (optional)
        self.slack_webhook_url = os.environ.get('SLACK_WEBHOOK_URL', '')
        
        # Start alert processor thread
        self.processor_thread = threading.Thread(target=self._process_alerts, daemon=True)
        self.processor_thread.start()
        
        # Start stats recording thread
        self.stats_thread = threading.Thread(target=self._record_stats, daemon=True)
        self.stats_thread.start()
        
        # NO DEMO MODE - Only real alerts from monitors
        print("✅ Alert Manager initialized - REAL ALERTS ONLY")
        print("   Alerts will only be generated by actual network/host monitors")
    
    def _record_stats(self):
        """Record alert counts for trending"""
        import time
        while True:
            try:
                # Get current counts
                critical = Alert.query.filter_by(severity='critical', is_resolved=False).count()
                high = Alert.query.filter_by(severity='high', is_resolved=False).count()
                medium = Alert.query.filter_by(severity='medium', is_resolved=False).count()
                low = Alert.query.filter_by(severity='low', is_resolved=False).count()
                
                self.alert_counts_history.append({
                    'timestamp': datetime.utcnow().isoformat(),
                    'critical': critical,
                    'high': high,
                    'medium': medium,
                    'low': low,
                    'total': critical + high + medium + low
                })
                
                time.sleep(60)  # Record every minute
            except Exception as e:
                print(f"Error recording stats: {e}")
                time.sleep(60)
    
    def send_alert(self, alert):
        """Queue alert for processing"""
        self.alert_queue.put(alert)
        self.alert_history.append({
            'alert': alert,
            'timestamp': datetime.utcnow()
        })
        
        # Update counters
        self.alert_count += 1
        if alert.severity == 'critical':
            self.critical_count += 1
        elif alert.severity == 'high':
            self.high_count += 1
        elif alert.severity == 'medium':
            self.medium_count += 1
        else:
            self.low_count += 1
            
        print(f"📢 REAL ALERT: {alert.severity} - {alert.description[:50]}...")
    
    def _process_alerts(self):
        """Process alerts from queue"""
        while True:
            try:
                alert = self.alert_queue.get(timeout=5)
                
                # Send notifications based on severity
                if alert.severity in ['critical', 'high']:
                    if self.email_enabled:
                        self._send_email_alert(alert)
                    if self.slack_enabled:
                        self._send_slack_alert(alert)
                elif alert.severity == 'medium' and self.email_enabled:
                    self._send_email_alert(alert)
                
                # Always log alerts
                self._log_alert(alert)
                    
            except queue.Empty:
                continue
            except Exception as e:
                print(f"Error processing alert: {e}")
    
    def _send_email_alert(self, alert):
        """Send email alert"""
        if not self.email_enabled or not self.sender_password:
            return
            
        try:
            msg = MIMEMultipart('alternative')
            msg['From'] = self.sender_email
            msg['To'] = ', '.join(self.admin_emails)
            msg['Subject'] = f"[{alert.severity.upper()}] Riley Falcon IDPS Alert - {alert.alert_type}"
            
            # Severity colors
            severity_colors = {
                'critical': '#e74a3b',
                'high': '#f6c23e',
                'medium': '#36b9cc',
                'low': '#1cc88a'
            }
            
            body = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                              color: white; padding: 20px; text-align: center; }}
                    .alert-box {{ 
                        background-color: {severity_colors.get(alert.severity, '#858796')}; 
                        color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px;
                    }}
                    table {{ width: 100%; border-collapse: collapse; }}
                    th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
                    th {{ background-color: #f8f9fc; }}
                    .footer {{ margin-top: 30px; font-size: 12px; color: #666; text-align: center; }}
                    .button {{
                        background-color: #4e73df;
                        color: white;
                        padding: 10px 20px;
                        text-decoration: none;
                        border-radius: 5px;
                        display: inline-block;
                        margin: 10px;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h2>🛡️ Riley Falcon Security Services</h2>
                    <h3>Intrusion Detection & Prevention System</h3>
                </div>
                
                <div class="content" style="padding: 20px;">
                    <div class="alert-box">
                        <h3>⚠️ {alert.severity.upper()} SECURITY ALERT</h3>
                        <p>{alert.description}</p>
                    </div>
                    
                    <table>
                        <tr><th>Alert ID</th><td>{alert.id}</td></tr>
                        <tr><th>Alert Type</th><td>{alert.alert_type}</td></tr>
                        <tr><th>Severity</th><td>{alert.severity.upper()}</td></tr>
                        <tr><th>Source</th><td>{alert.source}</td></tr>
                        <tr><th>Time (EAT)</th><td>{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}</td></tr>
                        <tr><th>Description</th><td>{alert.description}</td></tr>
                        <tr><th>Details</th><td><pre>{alert.details}</pre></td></tr>
                    </table>
                    
                    <div style="text-align: center; margin-top: 30px;">
                        <a href="http://localhost:5000/alerts" class="button">View Dashboard</a>
                        <a href="http://localhost:5000/resolve_alert/{alert.id}" class="button" style="background-color: #1cc88a;">Resolve Alert</a>
                    </div>
                </div>
                
                <div class="footer">
                    <p>© 2024 Riley Falcon Security Services - IT Department | East Africa Time</p>
                </div>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(body, 'html'))
            
            # Send email
            if self.sender_password:  # Only try if password is set
                server = smtplib.SMTP(self.smtp_server, self.smtp_port)
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
                server.quit()
                print(f"✅ Alert email sent for {alert.severity} alert")
            else:
                print(f"📧 Email would be sent (no password configured): {alert.severity} alert")
            
        except Exception as e:
            print(f"❌ Failed to send email alert: {str(e)}")
    
    def _send_slack_alert(self, alert):
        """Send alert to Slack"""
        if not self.slack_enabled or not self.slack_webhook_url:
            return
            
        try:
            import requests
            
            severity_colors = {
                'critical': '#e74a3b',
                'high': '#f6c23e',
                'medium': '#36b9cc',
                'low': '#1cc88a'
            }
            
            payload = {
                "attachments": [{
                    "color": severity_colors.get(alert.severity, '#858796'),
                    "title": f"[{alert.severity.upper()}] {alert.description}",
                    "fields": [
                        {"title": "Type", "value": alert.alert_type, "short": True},
                        {"title": "Source", "value": alert.source, "short": True},
                        {"title": "Time", "value": datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'), "short": True},
                        {"title": "Details", "value": alert.details[:200] + "...", "short": False}
                    ],
                    "footer": "Riley Falcon IDPS",
                    "ts": int(datetime.utcnow().timestamp())
                }]
            }
            
            response = requests.post(self.slack_webhook_url, json=payload)
            if response.status_code == 200:
                print(f"✅ Slack alert sent for {alert.severity} alert")
            else:
                print(f"❌ Failed to send Slack alert: {response.status_code}")
                
        except Exception as e:
            print(f"❌ Failed to send Slack alert: {e}")
    
    def _log_alert(self, alert):
        """Log alert to file"""
        try:
            log_entry = {
                'timestamp': datetime.utcnow().isoformat(),
                'id': alert.id,
                'severity': alert.severity,
                'type': alert.alert_type,
                'source': alert.source,
                'description': alert.description,
                'details': alert.details
            }
            
            # Create logs directory if it doesn't exist
            log_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'logs')
            os.makedirs(log_dir, exist_ok=True)
            
            log_file = os.path.join(log_dir, f"alerts_{datetime.utcnow().strftime('%Y%m')}.log")
            
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(log_entry) + '\n')
                
        except Exception as e:
            print(f"❌ Failed to log alert: {e}")
    
    def get_recent_alerts(self, limit=50):
        """Get recent alerts"""
        recent = list(self.alert_history)[-limit:]
        return [(item['timestamp'], item['alert']) for item in recent]
    
    def get_alert_statistics(self):
        """Get alert statistics"""
        # Get database counts for accuracy
        try:
            critical = Alert.query.filter_by(severity='critical', is_resolved=False).count()
            high = Alert.query.filter_by(severity='high', is_resolved=False).count()
            medium = Alert.query.filter_by(severity='medium', is_resolved=False).count()
            low = Alert.query.filter_by(severity='low', is_resolved=False).count()
            total = Alert.query.count()
            
            # Get last 24 hours count
            last_24h = datetime.utcnow() - timedelta(hours=24)
            last_24h_count = Alert.query.filter(Alert.timestamp > last_24h).count()
            
            # Get last hour count
            last_hour = datetime.utcnow() - timedelta(hours=1)
            last_hour_count = Alert.query.filter(Alert.timestamp > last_hour).count()
            
            # Count by type
            type_stats = db.session.query(Alert.alert_type, db.func.count(Alert.alert_type)).group_by(Alert.alert_type).all()
            by_type = {t: count for t, count in type_stats}
            
            # Count by source
            source_stats = db.session.query(Alert.source, db.func.count(Alert.source)).group_by(Alert.source).all()
            by_source = {s: count for s, count in source_stats}
            
            # Get trend data (last 12 hours)
            trend = []
            for i in range(12, 0, -1):
                hour_start = datetime.utcnow() - timedelta(hours=i)
                hour_end = hour_start + timedelta(hours=1)
                count = Alert.query.filter(Alert.timestamp.between(hour_start, hour_end)).count()
                trend.append(count)
            
            return {
                'total': total,
                'critical': critical,
                'high': high,
                'medium': medium,
                'low': low,
                'by_type': by_type,
                'by_source': by_source,
                'last_24h': last_24h_count,
                'last_hour': last_hour_count,
                'trend': trend,
                'history': list(self.alert_counts_history)
            }
            
        except Exception as e:
            print(f"Error getting alert statistics: {e}")
            return {
                'total': 0,
                'critical': 0,
                'high': 0,
                'medium': 0,
                'low': 0,
                'by_type': {},
                'by_source': {},
                'last_24h': 0,
                'last_hour': 0,
                'trend': [],
                'history': []
            }
    
    def resolve_alert(self, alert_id, user_id):
        """Resolve an alert"""
        try:
            alert = Alert.query.get(alert_id)
            if alert and not alert.is_resolved:
                alert.is_resolved = True
                alert.resolved_at = datetime.utcnow()
                alert.resolved_by = user_id
                db.session.commit()
                
                print(f"✅ Alert {alert_id} resolved by user {user_id}")
                return True
        except Exception as e:
            print(f"Error resolving alert: {e}")
        return False
    
    def get_trend_chart_data(self, hours=24):
        """Get data for trend charts"""
        try:
            labels = []
            critical_data = []
            high_data = []
            medium_data = []
            low_data = []
            
            for i in range(hours, 0, -1):
                hour_start = datetime.utcnow() - timedelta(hours=i)
                hour_end = hour_start + timedelta(hours=1)
                
                labels.append(hour_start.strftime('%H:00'))
                
                critical_data.append(Alert.query.filter(
                    Alert.severity == 'critical',
                    Alert.timestamp.between(hour_start, hour_end)
                ).count())
                
                high_data.append(Alert.query.filter(
                    Alert.severity == 'high',
                    Alert.timestamp.between(hour_start, hour_end)
                ).count())
                
                medium_data.append(Alert.query.filter(
                    Alert.severity == 'medium',
                    Alert.timestamp.between(hour_start, hour_end)
                ).count())
                
                low_data.append(Alert.query.filter(
                    Alert.severity == 'low',
                    Alert.timestamp.between(hour_start, hour_end)
                ).count())
            
            return {
                'labels': labels,
                'critical': critical_data,
                'high': high_data,
                'medium': medium_data,
                'low': low_data
            }
        except Exception as e:
            print(f"Error getting trend chart data: {e}")
            return {
                'labels': [],
                'critical': [],
                'high': [],
                'medium': [],
                'low': []
            }